src/live/douyu/douyu.go

当 cloudflare 源出错时, 换用中国大陆友好的 CDN 源

try close #77 #90

---

go.sum
src/cmd/bililive/internal/flag/flag.go
src/configs/config.go
src/listeners/event.go
src/listeners/listener.go
src/recorders/event.go
src/recorders/manager.go
src/recorders/manager_test.go
src/recorders/mock_test.go
src/recorders/recorder.go

再试一回, 尽量理解架构､ 逻辑, 不知是否理解得当｡ 
增补之处零零散散, 如有错漏恳请指正｡ 
单元测试确实是知识盲区, 或许稍后另作一 commit

add feature: split on room name changed

---

src/live/douyu/douyu.go

Douyu recently added the replay feature.

Ignore douyu replay status

---

src/live/twitch/twitch.go

twitch api v3 to v5 简单过渡.

---

src/live/acfun/acfun.go

https://api-new.app.acfun.cn/rest/app/live/info?authorId=36626547
```
{"result":105001,"error_msg":""}
```
https://live.acfun.cn/api/live/info?authorId=36626547
```
{"panoramic":false,"likeCount":46671,"title":"来啦来啦","cdnAuthBiz":0,"type":{"id":402,"name":"游戏","categoryId":4,"categoryName":"虚拟偶像"},"result":0,"requestId":"4378da657b9c4bdb949d8f77e42db3a1","action":40,"paidShowUserBuyStatus":false,"href":"36626547","onlineCount":342,"hasFansClub":true,"formatLikeCount":"4.7万","bizCustomData":"{\"typeId\":402,\"type\":[4,402]}","host-name":"hb2-acfun-kce-node28.aliyun","authorId":36626547,"portrait":false,"liveId":"U78ZGteJfBg","streamName":"kszt_uiTQWt8vtBI","createTime":1627219960038,"disableDanmakuShow":false,"formatOnlineCount":"342","coverUrls":["https://js-live.static.yximgs.com/bs2/ztl …
```

Update AcFun API

---

src/servers/handler.go

斗鱼桌面PC客户端直播间复制的直播间地址不带https，添加房间会失败

Add scheme to live url

---

src/configs/config.go
src/pkg/parser/ffmpeg/ffmpeg.go
src/pkg/parser/native/flv/flv.go
src/recorders/recorder.go

fix https://github.com/hr3lxphr6j/bililive-go/issues/102

使用户可以通过 config 文件设置 timeout 值

---

README.md
src/live/douyin/douyin.go

顺便更新了一下 README 文档，增加 config 中 cookie 的写法。
预计 fix https://github.com/hr3lxphr6j/bililive-go/issues/316

为抖音提供自定义cookie支持

---

Makefile
src/cmd/bililive/bililive.go
src/configs/config.go
src/configs/config_test.go
src/hack/build.sh
src/servers/handler.go
src/servers/server.go
src/webapp/dev_webapp.go
src/webapp/package.json
src/webapp/src/App.tsx
src/webapp/src/component/config-info/config-info.css
src/webapp/src/component/config-info/index.tsx
src/webapp/src/component/layout/index.tsx
src/webapp/src/utils/api.ts
src/webapp/webapp.go
src/webapp/yarn.lock

预计 fix https://github.com/hr3lxphr6j/bililive-go/issues/293
效果：

使 HTML 可以修改所有设置

---

src/hack/build.sh

fix https://github.com/hr3lxphr6j/bililive-go/issues/214

为 mips 设备增加 softfloat build 的可执行文件

---

docs/API.md
src/live/info.go
src/recorders/recorder.go
src/servers/handler.go
src/webapp/src/component/live-list/index.tsx

fix https://github.com/hr3lxphr6j/bililive-go/issues/219

修复 typo，把 recoding 改成 recording

---

docs/API.md
src/servers/handler.go
src/servers/utils.go

fix https://github.com/hr3lxphr6j/bililive-go/issues/303

fix 网页端保存设置的返回值格式，服务器端和前端的预期不同，导致前端命令行报错

---

src/webapp/src/component/live-info/index.tsx

fix https://github.com/hr3lxphr6j/bililive-go/issues/307

网页添加一键复制版本信息

---

src/live/huya/huya.go

fix https://github.com/hr3lxphr6j/bililive-go/issues/262, https://github.com/hr3lxphr6j/bililive-go/issues/291, https://github.com/hr3lxphr6j/bililive-go/issues/341
被封的房间效果如图

允许监控虎牙被封房间

---

src/cmd/bililive/internal/init.go
src/live/missevan/missevan.go

新增猫耳fm直播录制

---

README.md
src/cmd/bililive/internal/init.go
src/live/hongdoufm/hongdoufm.go

新增克拉克拉直播录制

---

src/live/douyin/douyin.go
src/pkg/utils/utils.go

也许能让抖音录制的成功率提高一点。
用户设置的 cookie 可以覆盖随机生成的默认 cookie

随机生成默认抖音cookie

---

src/pkg/parser/native/flv/tag_video.go
src/webapp/package.json

fix https://github.com/hr3lxphr6j/bililive-go/issues/393

refine flv-parser expectable error message

---

src/configs/config.go
src/pkg/parser/native/flv/flv.go
src/pkg/utils/functions.go
src/pkg/utils/strings.go
src/pkg/utils/utils.go
src/recorders/recorder.go

fix https://github.com/hr3lxphr6j/bililive-go/issues/392, https://github.com/hr3lxphr6j/bililive-go/issues/337,

更加兼容windows的文件名规则，可选的替换特殊文件名功能

---

src/live/info.go
src/live/missevan/missevan.go
src/recorders/recorder.go

Change the default recording format of missevan to aac

---

src/live/douyu/douyu.go

增加详细斗鱼错误信息

---

src/webapp/src/component/live-list/index.tsx

Add filters for platform and status, fix typo error #230 #340

add filters for platform and status, fix typo error

---

src/live/douyin/douyin.go

fixed: 修复抖音无法获取监控信息的问题

---

src/live/huya/huya.go
src/pkg/parser/native/flv/flv.go

fix https://github.com/hr3lxphr6j/bililive-go/issues/638

增加虎牙获取直播信息过程中的错误处理，为flv parser设置 header 以支持虎牙直播录制

---

src/live/douyin/douyin.go

修正获取抖音的备选方法

---

src/webapp/src/component/live-list/index.tsx

默认排序改成录制中排最前面

---

src/live/douyin/douyin.go

fix https://github.com/hr3lxphr6j/bililive-go/issues/735

fix douyin hidden live

---

src/live/huya/huya.go

对 https://github.com/hr3lxphr6j/bililive-go/pull/764 的一些边缘情况的补充

fix huya edge case

---

README.md
src/pkg/parser/ffmpeg/ffmpeg.go

预计会修复几个陈年 bug issue。
先 release 了然后观望一段时间，没问题的话再关闭相关 issue。

fix ffmpeg race panic

---

src/cmd/bililive/bililive.go
src/listeners/manager_test.go
src/listeners/mock_test.go
src/live/huya/implForXingXiu.go
src/live/mock/mock.go
src/recorders/manager_test.go
src/recorders/mock_test.go

感谢 @wwkk2580 大佬在 https://github.com/ihmily/DouyinLiveRecorder/pull/993 提出的解决方案！

修复虎牙星秀颜值舞蹈区2分钟分段问题。
